name: paramount
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1 # Ensure your Flutter SDK is also up-to-date (flutter upgrade)

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2 # Updated to latest stable
  # Firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  # Cloudinary for file storage (replaces Firebase Storage)
  cloudinary_public: ^0.21.0
  http: ^1.1.0
  # Image handling
  image_picker: ^1.0.7
  url_launcher: ^6.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Updated to latest stable

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Oswald-VariableFont_wght
      fonts:
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf
    