name: paramount
description: "An enhanced Flutter project for Paramount Institute, providing robust features for student and teacher management."

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Aapke app ko publicly publish hone se rokta hai

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the product and file version while build-number is used as the build revision.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Flutter SDK range ko update kiya, latest stable versions ke liye

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons font-family, iOS style icons ke liye.
  cupertino_icons: ^1.0.8

  # Firebase dependencies - Backend services ke liye.
  firebase_core: ^2.24.2 # Firebase core functionality
  firebase_auth: ^4.15.3 # User authentication ke liye
  cloud_firestore: ^4.13.6 # NoSQL database
  firebase_messaging: ^14.7.10 # Push notifications ke liye
  firebase_analytics: ^10.7.4 # App usage analytics ke liye

  # Cloudinary for file storage - Firebase Storage ki jagah.
  cloudinary_public: ^0.21.0 # Cloudinary API se interact karne ke liye

  # Network requests ke liye.
  http: ^1.1.0 # HTTP requests send aur receive karne ke liye

  # Image selection from gallery/camera ke liye.
  image_picker: ^1.0.7

  # URLs launch karne ke liye (e.g., email, phone calls, web links).
  url_launcher: ^6.2.2

  # Circular progress bar aur indicators ke liye (StudentAttendancePage mein use kiya gaya).
  percent_indicator: ^4.2.3 # Ye dependency add ki hai

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code quality aur linter rules ke liye.
  flutter_lints: ^3.0.1 # Latest stable version use kiya

# The following section is specific to Flutter.
flutter:
  # 'flutter generate' command ke liye assets aur fonts specify karein.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ # Saari images is folder se load hongi
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # For details regarding assets and for adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Oswald # Font family ka naam
      fonts:
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf # Font file ka path
          weight: 400 # Optional: font weight specify kar sakte hain agar variable font hai
          # style: italic # Optional: font style specify kar sakte hain
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
