// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIZ_ZfclwNnHr-opU5enlRLNq7Fbhpuzg',
    appId: '1:929885803027:web:9e8dbd83e5bc8b585b65e6',
    messagingSenderId: '929885803027',
    projectId: 'paramount-classes-8d18d',
    authDomain: 'paramount-classes-8d18d.firebaseapp.com',
    storageBucket: 'paramount-classes-8d18d.firebasestorage.app',
    measurementId: 'G-SYP5JH51KK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg09uafOmZh1aeL2TggUJbizxtLXazdfo',
    appId: '1:929885803027:android:4ff20d9678cbd5cd5b65e6',
    messagingSenderId: '929885803027',
    projectId: 'paramount-classes-8d18d',
    storageBucket: 'paramount-classes-8d18d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgr8nayhBz-51aThBMqpLI8Xlx40WJO0I',
    appId: '1:929885803027:ios:f2ee513694bc8afb5b65e6',
    messagingSenderId: '929885803027',
    projectId: 'paramount-classes-8d18d',
    storageBucket: 'paramount-classes-8d18d.firebasestorage.app',
    iosClientId: '929885803027-f2f4pi0ifetbrg6lh5du9r3sgv9hgun5.apps.googleusercontent.com',
    iosBundleId: 'com.example.paramount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgr8nayhBz-51aThBMqpLI8Xlx40WJO0I',
    appId: '1:929885803027:ios:f2ee513694bc8afb5b65e6',
    messagingSenderId: '929885803027',
    projectId: 'paramount-classes-8d18d',
    storageBucket: 'paramount-classes-8d18d.firebasestorage.app',
    iosClientId: '929885803027-f2f4pi0ifetbrg6lh5du9r3sgv9hgun5.apps.googleusercontent.com',
    iosBundleId: 'com.example.paramount',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIZ_ZfclwNnHr-opU5enlRLNq7Fbhpuzg',
    appId: '1:929885803027:web:42ec5e4898f4862e5b65e6',
    messagingSenderId: '929885803027',
    projectId: 'paramount-classes-8d18d',
    authDomain: 'paramount-classes-8d18d.firebaseapp.com',
    storageBucket: 'paramount-classes-8d18d.firebasestorage.app',
    measurementId: 'G-NFZJJ2PTTK',
  );

}
